# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
- group: DeployGroup


pool:
  vmImage: windows-latest
  name: 'MyLearning'


stages:
- stage: Build
  displayName: 'VS Build'
  jobs:
  - job: BuildJob
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
      
    - task: PublishPipelineArtifact@1
      displayName: 'Publish artifact'
      inputs:
        targetPath: 'C:\Users\vmuser1\Documents\Naval\Publish'
        artifact: $(artifactName)

    # - task: CopyFiles@2
    #   inputs:
    #     SourceFolder: 'C:\Users\vmuser1\Documents\Naval\Build\1\s\DashBoard_MVC'
    #     Contents: '**\*'
    #     TargetFolder: 'C:\Users\vmuser1\Documents\Naval\app.publish'
    #     OverWrite: true
    #     CleanTargetFolder: true

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
  
- stage: Deploy_To_SYST2
  displayName: 'Deploy'
  dependsOn: Build
  condition: succeeded('Build')  
  jobs:
  - deployment: DeployJob
    environment: 
     name: SYST2
     resourceType: VirtualMachine
  
    strategy:
     runOnce:
       deploy:
         steps:
         - task: DownloadPipelineArtifact@2
           displayName: 'Download artifact'
           inputs:
             targetPath: 'C:\Users\vmuser1\Documents\Naval\app.publish'
          
         - task: IISWebAppManagementOnMachineGroup@0
           displayName: 'Deploy to Stage Environment'
           inputs:            
              WebsiteName: 'MyWeb'  
              AppPoolName: 'MyWeb'
              IISDeploymentType: 'IISApplicationPool'
              ActionIISApplicationPool: 'RecycleAppPool'
              StartStopRecycleAppPoolName: 'MyWeb'
